
GET http://localhost:5224/games

###
GET http://localhost:5224/games/4

###
POST http://localhost:5224/games
Content-Type: application/json
{
    "name": "Battlefield 1",
    "genre": "FPS",
    "price": 499.00,
    "releaseDate": "2016-08-30"
}